@startuml
object Scene0
object Scene1
object Scene2
object Scene3
object Scene4
object Scene5
object Scene6
object Scene7
object Scene8
object Scene9
object Scene10
object Scene11
object Scene12
object Scene13
object Scene14
object Scene15
object Scene16
object Scene17
object Scene18
object Scene19
object Scene20
object Scene21
object Scene22
object Scene23
object fail
object fail2
object fail3
object fail4
object fail5
object fail6
object fail7
object fail8





Scene1 <|-- Scene0 : A
Scene2 <|-- Scene0 : B
Scene3 <|-- Scene1 : A
fail   <|-- Scene1 : B
Scene3 <|-- Scene2 : A
fail   <|-- Scene2 : B
Scene4 <|-- Scene3 : A
fail   <|-- Scene3 : B
Scene5 <|-- Scene4 : A
fail2  <|-- Scene4 : B
Scene6 <|-- Scene5 : A
fail   <|-- Scene5 : B
Scene7 <|-- Scene6 : A
fail3  <|-- Scene6 : B
Scene8 <|-- Scene7 : A
Scene9 <|-- Scene7 : B
Scene10 <|-- Scene8 : A
Scene11 <|-- Scene8 : B
Scene8  <|-- Scene9 : A
Scene8  <|-- Scene9 : B
Scene11 <|-- Scene10 : A
Scene11 <|-- Scene10 : B
Scene12 <|-- Scene11 : A
fail4   <|-- Scene11 : B
Scene13 <|-- Scene12 : A
fail5   <|-- Scene12 : B
Scene14 <|-- Scene13 : A
Scene15 <|-- Scene13 : B
Scene16 <|-- Scene14 : A
Scene17 <|-- Scene14 : B
Scene16 <|-- Scene15 : A
Scene17 <|-- Scene15 : B
Scene17 <|-- Scene16 : A
Scene18 <|-- Scene17 : A
Scene19 <|-- Scene17 : B
Scene20 <|-- Scene18 : A
Scene21 <|-- Scene18 : B
Scene20 <|-- Scene19 : B
fail6   <|-- Scene19 : B
Scene21 <|-- Scene20 : A
fail7   <|-- Scene20 : B
Scene22 <|-- Scene21 : A
Scene23 <|-- Scene22 : A
fail8   <|-- Scene22 : B










@enduml
