@startuml
object Scene0 {
    "You are Tony Stark, a billionare that is trapped in a cave by terrorist..."
}

object Scene1 {
    "Tony realizes that he is connected to a battery..."
}

object Scene2 {
    "In shock to Tony's response, Yinsen turns away from Tony..."
}

object Scene3 {
    "Dazed and confused you begin to zip up your coat..."
}

object Scene4 {
    "Tony begins to think of a plan, he gazes over to Yinsen..."
}

object Scene5 {
    "Moving closer to the fire, Tony rubs his chest where the he thinks about his legacy..."
}

object Scene6 {
    "Tony and Yinsen sit together by the fire, quietly going over there master plan to escape..."
}

object Scene7 {
    "As Tony and Yinsen discuss the plan, Tony starts to make a list of conpomtants to build the Armored suit..."
}

object Scene8 {
    "As Tony and Yinsen begin to collect and discuss plans to escape footsteps are heard approaching..."
}

object Scene9 {
    "Yinesen: Tony you must start trusting me for this plan to work!"
}

object Scene10 {
    "Raza: The 10 rings have been around before MANKIND!! We have inflitrated every body of you Americas pityful goverment; We are a organization of faith, you will soon see Tony..."
}

object Scene11 {
    "As Raza contiues the story of the 10 rings Tony begins to reliaze how inportant his plan to esacpe is..."
}

object Scene12 {
    "With numbered days Raza and the 10 rings expect their weapons to be complete..."
}

object Scene13 {
    "With time counting down, Tony and Yinesen begin to assembly the suit on Tony. Simultanesuly Raza sees somthing Suspicious on Camera, he send soilders to go check..."
}

object Scene14 {
    "The Battle begins! Tony shoots a missle towards Raza, The blast throws him..."
}

object Scene15 {
    "The Battle begins! Tony shoots a missle towards Raza, The blast throws him..."
}

object Scene16 {
    "Tony moves forward wondering through the cave searching for Yinesen..."
}

object Scene17 {
    "Yinsen dies. Tony turns angry..."
}

object Scene18 {
    "Tony shoots fire at the men and their camp from his suit. The men continue to shoot at Tony..."
}

object Scene19 {
    "Tony shoots fire at the men and their camp from his suit. The men continue to shoot at Tony..."
}

object Scene20 {
    "Tony then is seen wondering through the desert, exhausted. Military helicopters fly up from behind him..."
}

object Scene21 {
    "As one of the helicopters lands, Tony collapses to his knees, holding up a peace sign..."
}

object Scene22 {
    "Now that Tony is home and safe he begins to realize he has a bigger purpose in life. As he gets ready for a press conference Rhodes begins to pressure to not tell anyone about the suit..."
}

object Scene23 {
    "WINNING SCENARIO"
}

object fail
object fail2
object fail3
object fail4
object fail5
object fail6
object fail7
object fail8





Scene1 <|-- Scene0 : A
Scene2 <|-- Scene0 : B
Scene3 <|-- Scene1 : A
fail   <|-- Scene1 : B
Scene3 <|-- Scene2 : A
fail   <|-- Scene2 : B
Scene4 <|-- Scene3 : A
fail   <|-- Scene3 : B
Scene5 <|-- Scene4 : A
fail2  <|-- Scene4 : B
Scene6 <|-- Scene5 : A
fail   <|-- Scene5 : B
Scene7 <|-- Scene6 : A
fail3  <|-- Scene6 : B
Scene8 <|-- Scene7 : A
Scene9 <|-- Scene7 : B
Scene10 <|-- Scene8 : A
Scene11 <|-- Scene8 : B
Scene8  <|-- Scene9 : A
Scene8  <|-- Scene9 : B
Scene11 <|-- Scene10 : A
Scene11 <|-- Scene10 : B
Scene12 <|-- Scene11 : A
fail4   <|-- Scene11 : B
Scene13 <|-- Scene12 : A
fail5   <|-- Scene12 : B
Scene14 <|-- Scene13 : A
Scene15 <|-- Scene13 : B
Scene16 <|-- Scene14 : A
Scene17 <|-- Scene14 : B
Scene16 <|-- Scene15 : A
Scene17 <|-- Scene15 : B
Scene17 <|-- Scene16 : A
Scene18 <|-- Scene17 : A
Scene19 <|-- Scene17 : B
Scene20 <|-- Scene18 : A
Scene21 <|-- Scene18 : B
Scene20 <|-- Scene19 : B
fail6   <|-- Scene19 : B
Scene21 <|-- Scene20 : A
fail7   <|-- Scene20 : B
Scene22 <|-- Scene21 : A
Scene23 <|-- Scene22 : A
fail8   <|-- Scene22 : B










@enduml
